### ISSUE TITLE
balance of materials and drops

### ISSUE THREAD

**Issue by chrcoluk** [Bartz24/FF13Randomizer#2]
I am halfway through chapter 11.

Feedback

I have most of the shops but still dont have the garage, which means I cannot buy mechanical materials.
95% of enemies are dropping either non mechanical materials, or equipment.  
I got my first chest in the entire game containing mechanical materials in chapter 11.
In short this has meant I have not been able to do barely any upgrading.
Meanwhile I have 600k, from selling excess weapons that just keep dropping.
Also i didnt get any accessory or atb nodes until chapter 11, seems they too weighted towards late stage development.  I then got 3 accessory nodes on 4 out of 6 characters, and 2 on the other 2 all in chapter 11.

I would replace most weapon drops with mechanical materials, which definitely need a big boost.

Also I would like a overall drop rate boost from monsters, so the game is less grindy, common drops maybe set to 66% base for every non boss enemy.  It really should be very high.

**Comment by Bartz24** [comment]
the balance of drops has been adjusted a fair bit to address these issues, so if you ever feel like playing around again, let me know how the balance feels now!

I can add a flag to control drop rates. Thanks for the feedback!
