### ISSUE TITLE
boss battles wrong or no drops

### ISSUE THREAD

**Issue by chrcoluk** [Bartz24/FF13Randomizer#4]
boss at end of chapter 3 was meant to drop lionheart weapon got no drop.
boss pair at end of chapter 6 was meant to drop black belt and magician mark, but instead got giant glove and iron bangle.

seed is 465563428

**Comment by Bartz24** [comment]
So, drop chances aren't modified, but some bosses don't have guarenteed drops.
As for getting the "wrong" drops, the game splits different phases of some enemies and bosses as their own entry.
Ex: each phase of protoflorian is a separate "enemy" in the data. Each phase has a different drop, and the phase you actually kill will be drops you get.  The info in the datalog may be incorrect, but if you check the libra during battle before kill, those drops will be accurate.

I'll be adding logic to keep drops the same across phases, but I need to do a lot more work on the backend before I can do so.  which will probably be done for the next major version 1.7.0
