### ISSUE TITLE
1.9.0.Pre-2 controller type button prompts

### ISSUE THREAD

**Issue by daionor** [Bartz24/FF13Randomizer#7]
Apparently something in the code makes the controller button visualization for menus not work, only allowing keyboard button visuals. Not sure what could cause this, but something to look into. For example, on the cutscene pause menu where it would have usually "<select>: skip <start>: resume", it instead just shows ": skip      : resume". It didn't do this on the last release I had of this, and didn't do it last time I ran it without randomizing (just a few weeks ago to make sure it completely removed the old rando since I was waiting for the next release).

**Comment by Bartz24** [comment]
This is a PC port issue, sometimes reloading the game and loading a game with controller prompts set already fixes it.
